### PR TITLE
Fix #52: time.clock() has been removed in python 3.8

### LINKED ISSUE #52: nmlc doesn't work with python 3.8
time.clock has been removed in python 3.8, generating `Error:    (AttributeError) "module 'time' has no attribute 'clock'".`

### PR DESCRIPTION
**Pull request by glx22**

### CODE REVIEW

**Comment by nielsmh** [comment]
This is used to update progress messages once in a while, right? Wouldn't a wall clock time instead of a process time stopwatch be better? E.g. `time.monotinic()`.
