### ISSUE TITLE
nmlc doesn't work with python 3.8

### ISSUE THREAD

**Issue by glx22** [OpenTTD/nml#52]
time.clock has been removed in python 3.8, generating `Error:    (AttributeError) "module 'time' has no attribute 'clock'".`
